apiVersion: v1
kind: Service
metadata:
  name: helloworld
  labels:
    run: helloworld
spec:
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    app: helloworld
  type: LoadBalancer

